/*
 * Data Catalog Service - Asset Details
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	clientv3 "go.etcd.io/etcd/client/v3"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	conf map[interface{}]interface{}
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService(conf map[interface{}]interface{}) DefaultApiServicer {
	uuidStr := fmt.Sprint(conf["uuid"])
	fmt.Printf("Value: %s\n", uuidStr)
	fmt.Printf("Value: %s\n", conf["etcd_hostname"])
	fmt.Printf("Value: %d\n", conf["etcd_port"])
	fmt.Printf("Value: %s\n", conf["etcd_username"])
	fmt.Printf("Value: %s\n", conf["etcd_password"])
	return &DefaultApiService{conf}
}

func (s *DefaultApiService) getEtcdClient() *clientv3.Client {
	var conf clientv3.Config

	if s.conf["etcd_username"] != nil && s.conf["etcd_password"] != nil {
		conf = clientv3.Config{
			Endpoints: []string{"localhost:2379"},
		}
	} else {
		conf = clientv3.Config{
			Endpoints: []string{"localhost:2379"},
		}
	}
	cli, err := clientv3.New(conf)

	if err != nil {
		// handle error!
	}

	return cli
}

// CreateAsset - This REST API writes data asset information to the data catalog configured in fybrik
func (s *DefaultApiService) CreateAsset(ctx context.Context, xRequestDatacatalogWriteCred string, createAssetRequest CreateAssetRequest, bodyBytes []byte) (ImplResponse, error) {
	// TODO - update CreateAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, CreateAssetResponse{}) or use other options such as http.Ok ...
	//return Response(201, CreateAssetResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	assetID := createAssetRequest.DestinationCatalogID + "/" + createAssetRequest.DestinationAssetID
	fmt.Println(string(bodyBytes))

	return Response(201, CreateAssetResponse{AssetID: assetID}), nil
}

// DeleteAsset - This REST API deletes data asset
func (s *DefaultApiService) DeleteAsset(ctx context.Context, xRequestDatacatalogCred string, deleteAssetRequest DeleteAssetRequest) (ImplResponse, error) {
	// TODO - update DeleteAsset with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, DeleteAssetResponse{}) or use other options such as http.Ok ...
	//return Response(200, DeleteAssetResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteAsset method not implemented")
}

// GetAssetInfo - This REST API gets data asset information from the data catalog configured in fybrik for the data sets indicated in FybrikApplication yaml
func (s *DefaultApiService) GetAssetInfo(ctx context.Context, xRequestDatacatalogCred string, getAssetRequest GetAssetRequest) (ImplResponse, error) {
	// TODO - update GetAssetInfo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetAssetResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetAssetResponse{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAssetInfo method not implemented")
}
